version: "3.9"

services:
  chatbot:
    build: .
    container_name: oribuyin-chatbot
    restart: always
    env_file:
      - .env
    ports:
      - "8000:8000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
